[build]
  functions = "functions"
  publish = "public"
  command = """
    mkdir -p functions && \
    go mod tidy && \
    go mod verify && \
    go mod download && \
    go build -o functions/rangeImage ./functions/rangeImage.go
  """

# 环境变量配置
[build.environment]
  GO_VERSION = "1.19"
  GO111MODULE = "on"
  # 不要在配置文件中暴露数据库连接字符串
  # 请在Netlify后台设置环境变量
  MONGODB_URI = "${MONGODB_URI}"

# API重定向规则
[[redirects]]
  from = "/status"
  to = "/.netlify/functions/rangeImage"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/img"
  to = "/.netlify/functions/rangeImage"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# 404处理
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# 请求头设置
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Access-Control-Allow-Origin = "*"
    Cache-Control = "no-store"
    Strict-Transport-Security = "max-age=31536000"
    Vary = "Accept, Origin, query"