[build]
  # 指定函数目录
  functions = "functions"
  # 构建命令
  command = "npm run build"
  # 发布目录
  publish = "public"

# 开发环境设置
[dev]
  framework = "#custom"
  targetPort = 3000
  port = 8888
  publish = "public"
  autoLaunch = true

# 环境变量配置
[build.environment]
  NODE_VERSION = "18"

# API重定向规则
[[redirects]]
  from = "/img"
  to = "/.netlify/functions/rangeImage"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# 404处理
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# 请求头设置
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Access-Control-Allow-Origin = "*"
    Cache-Control = "no-store"
    Strict-Transport-Security = "max-age=31536000"
    Vary = "Accept, Origin, query"